version: '3.7'

x-minio-common: &minio-common # 'x-minio-common' is a custom extension. '&minio-common' is an anchor. These allows for config to be applied to multiple services within the compose file. 
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" data1
  expose:
    - "9000"
    - "9090"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common # anchor is used here to apply previouly defined config
    hostname: minio-docker-compose
    container_name: minio1
    volumes:
      - ./minio-data1:/data1
    ports:
      - "9100:9000"
      - "9190:9090"
  minio2:
    <<: *minio-common
    hostname: minio-docker-compose
    container_name: minio2
    volumes:
      - ./minio-data2:/data2
    ports:
      - "9200:9000"
      - "9290:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prom
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom-data:/prometheus